version: '3.8'

services:
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      HTTP_ADDR: ":8080"
      DEBUG_ERRORS: 1
      DSN: "postgres://postgres:password@postgres/bookshop?sslmode=disable"
      MIGRATIONS_PATH: "file://migrations"
    command: ["./wait-for-it.sh", "postgres:5432", "--timeout=60", "--", "./app"]

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookshop
    volumes:
      - ./internal/pg/data:/var/lib/postgresql/data